#!/usr/bin/env python3
"""
Concatenate the backend into one file, so setting it up is one paste.

Apps Script shares a single global scope across every file in a project, so
eight files and one file behave identically. The split is for reading; the
concatenation is for setting up on a phone-sized attention span in a Partner
Center tab.

Generated rather than maintained by hand, because a hand-copied combined file
drifts from the sources the moment anything changes — and the divergence would
only show up as behaviour that does not match the tests.

    python3 apps-script/build-single-file.py
"""
import pathlib
import datetime
import subprocess

HERE = pathlib.Path(__file__).parent
OUT = HERE / 'TikShopBackend.gs'

# Config first so the constants read before the code that uses them. Not
# required — one global scope, and function declarations hoist — but a human
# reading top to bottom deserves the definitions first.
ORDER = [
    'Config.gs',
    'Errors.gs',
    'Lock.gs',
    'Sheet.gs',
    'Auth.gs',
    'TikTok.gs',
    'Product.gs',
    'Orders.gs',
    'Export.gs',
    'Api.gs',
]

missing = [name for name in ORDER if not (HERE / name).exists()]
if missing:
    raise SystemExit(f'missing source files: {", ".join(missing)}')

parts = [f'''/**
 * TikShop backend — all {len(ORDER)} files concatenated into one.
 *
 * GENERATED by apps-script/build-single-file.py on {datetime.date.today()}.
 * Do not edit this file. Edit the sources and regenerate, or the two diverge
 * and the tests stop describing what is deployed.
 *
 * Paste this as a single script file in a NEW Apps Script project, replace the
 * appsscript.json manifest, then run setupSheets() followed by checkSetup().
 *
 * DO NOT paste it into Sheldon Delivery API. That project already defines
 * doGet, doPost, handle_, json_ and WRITE_ACTIONS, and Apps Script shares one
 * global scope across files — so the two collide on all five. WRITE_ACTIONS is
 * a const there, which is a hard redeclaration error, and Painting Matters
 * would lose delivered-status and POD sync.
 *
 * Sources, in order:
{chr(10).join(f" *   {i + 1}. {name}" for i, name in enumerate(ORDER))}
 */
''']

# The commit the paste came from, stamped into the file and served by `ping`.
#
# Without it there is no way to tell a pasted backend from a stale one — not
# from the app, not from a probe, not from checkSetup. So "have you pasted it
# yet" was answered by asking Brien, and a stale backend looked exactly like a
# bug in the fix that was never deployed. `git describe --always --dirty` so an
# uncommitted build is labelled as one.
try:
    SHA = subprocess.run(
        ['git', 'describe', '--always', '--dirty', '--abbrev=7'],
        cwd=HERE, capture_output=True, text=True, check=True,
    ).stdout.strip()
except Exception:
    SHA = 'unknown'

for name in ORDER:
    body = (HERE / name).read_text().rstrip()
    rule = '=' * (72 - len(name))
    parts.append(f'\n// {rule} {name}\n\n{body}\n')

OUT.write_text('\n'.join(parts))
# Appended last so the line count in the message counts it.
BUILD = f"{SHA} {datetime.date.today()}"
with OUT.open('a') as fh:
    fh.write(
        '\n// ======================================================= build stamp\n\n'
        '/** Which paste is running. Served by `ping` and printed by checkSetup. */\n'
        f"var BACKEND_BUILD = '{BUILD}';\n"
    )
lines = OUT.read_text().count('\n')
print(f'wrote {OUT.name} — {len(ORDER)} files, {lines} lines, {OUT.stat().st_size // 1024} KB, build {BUILD}')
