/**
 * TikShop backend — all 8 files concatenated into one.
 *
 * GENERATED by apps-script/build-single-file.py on 2026-09-06.
 * Do not edit this file. Edit the sources and regenerate, or the two diverge
 * and the tests stop describing what is deployed.
 *
 * Paste this as a single script file in a NEW Apps Script project, replace the
 * appsscript.json manifest, then run setupSheets() followed by checkSetup().
 *
 * DO NOT paste it into Sheldon Delivery API. That project already defines
 * doGet, doPost, handle_, json_ and WRITE_ACTIONS, and Apps Script shares one
 * global scope across files — so the two collide on all five. WRITE_ACTIONS is
 * a const there, which is a hard redeclaration error, and Painting Matters
 * would lose delivered-status and POD sync.
 *
 * Sources, in order:
 *   1. Config.gs
 *   2. Lock.gs
 *   3. Sheet.gs
 *   4. Auth.gs
 *   5. TikTok.gs
 *   6. Product.gs
 *   7. Export.gs
 *   8. Api.gs
 */


// =============================================================== Config.gs

/**
 * TikShop backend — configuration.
 *
 * Runs as the deploying user, which is what gives it native access to the
 * shared drive and the Sheet without a service account. A service account
 * would have to be added as a member of the shared drive separately; running
 * as the user avoids that entirely.
 *
 * Conventions follow Sheldon Delivery API so the two projects stay legible
 * side by side: {PREFIX}_ Script Properties, a ?action= JSON router, and
 * LockService around anything that writes.
 */

/** Shared drive folder: "TikTok Livestream Buddy". */
var DRIVE_ROOT_ID = '1DMzpmTKGkBmAW2j_yaFJffKXIHZJU_ix';
var EXPORTS_FOLDER_ID = '1Jx5XCZqwnv4JT9_6w3M9eUC42In8mmGq';
var PHOTOS_FOLDER_ID = '1-bLKle65JB9Loqbi8wyF5cd2n8hZQ6AG';
var DATA_SHEET_ID = '1GRYYUP7NdgCwTIgt3UHiPh4K-cerNvo-PHQZfGUs2Jg';

var TT_HOST = 'https://open-api.tiktokglobalshop.com';
var TT_AUTH_HOST = 'https://auth.tiktok-shops.com';

/**
 * The three shops. Prefixes match Sheldon Delivery API's Script Properties, so
 * if the same app registrations are reused the credentials are already there.
 */
// `authorizeFn` names the toolbar function that starts this shop's consent
// flow. It is here rather than built from the id because checkSetup has to
// print a name a person can actually pick from the Run dropdown — and the one
// it used to print, ttAuthorizeUrl('HZ'), cannot be run that way at all, since
// the editor has no way to pass an argument.
var SHOPS = [
  { id: 'HZ', brand: 'HOUZE',            handle: '@houze.com.sg',    entity: 'Sheldon Global Pte Ltd', authorizeFn: 'authorizeHOUZE' },
  { id: 'TM', brand: 'Table Matters',    handle: '@tablematterssg',  entity: 'Audrey Global Pte Ltd',  authorizeFn: 'authorizeTableMatters' },
  // Painting Matters' legal entity is not recorded in the vault yet. Left
  // blank rather than guessed — a wrong entity is corrosive once exports
  // become purchase orders.
  { id: 'PM', brand: 'Painting Matters', handle: '@paintingmatters', entity: '', authorizeFn: 'authorizePaintingMatters' }
];

/** Singapore listing constraints, enforced before anything reaches TikTok. */
var TITLE_MIN = 25;
var TITLE_MAX = 255;
var CURRENCY = 'SGD';
var WEIGHT_UNIT = 'KILOGRAM';
var DIMENSION_UNIT = 'CENTIMETER';
var CATEGORY_VERSION = 'v2';

/** Fixed shipping declaration. Not shown in the form; see the decision note. */
var DEFAULT_WEIGHT_KG = '1';
var DEFAULT_DIMS = { length: '10', width: '10', height: '10' };

/**
 * A livestream is ONE TikTok product, and each SKU called out on air is a
 * variation of it.
 *
 * TikTok allows variation images on exactly one sales-attribute type per
 * product, and requires an image for every value of it — so one attribute with
 * one value per SKU is the shape that works, and it is what the buyer sees as
 * a gallery of photos to tap.
 */
var VARIANT_ATTRIBUTE_NAME = 'Design';   // max 20 chars, English only
var VALUE_NAME_MAX = 50;                 // sales_attributes.value_name

/**
 * Variations per product. Singapore gets 100 — "Max SKUs for BR, EU, JP, MX,
 * UK, US: 300. Max SKUs for other regions: 100" — so a 200-SKU factory run
 * needs a continuation listing, and finding that out at SKU 101 mid-broadcast
 * would be the worst possible moment.
 */
var MAX_SKUS_PER_PRODUCT = 100;

/** Sheet tab names. */
var TAB_LISTINGS = 'Listings';
var TAB_SKUS = 'SKUs';
var TAB_LOG = 'Log';
var TAB_USERS = 'Users';

/**
 * Who owns the allowlist. Seeded as admin on first run so there is always one
 * account that can approve others.
 */
var OWNER_EMAIL = 'brienchua@sheldonglobal.com';

/** Roles, most to least privileged. */
var ROLE_ADMIN = 'admin';    // can list, export, and approve people
var ROLE_LISTER = 'lister';  // can list and export
var ROLE_PENDING = 'pending';// signed in, waiting for approval, can do nothing
var ROLE_BLOCKED = 'blocked';

function props_() { return PropertiesService.getScriptProperties(); }
/**
 * Read a script property.
 *
 * Trimmed, because these are pasted by hand out of consoles that helpfully
 * append a newline. An untrimmed client id compares unequal to the same id
 * inside a token, and the only symptom is that sign-in silently fails — which
 * is exactly the kind of fault that costs an evening.
 */
function prop_(k) { return String(props_().getProperty(k) || '').trim(); }
function setProps_(o) { props_().setProperties(o, false); }

function shopById_(id) {
  for (var i = 0; i < SHOPS.length; i++) if (SHOPS[i].id === id) return SHOPS[i];
  return null;
}

/**
 * One-click setup check.
 *
 * Run this from the Apps Script editor after pasting the code and filling in
 * the properties. It reports everything the app needs and says which pieces
 * are missing, so the setup is verified in one run rather than by working
 * through a checklist and hoping.
 *
 * Deliberately reports rather than throws: the first missing property should
 * not hide the other eight. And it never prints a secret — only whether one is
 * present — because the execution log is a place things get pasted from.
 */
function checkSetup() {
  var lines = [];
  var problems = 0;

  function ok(label) { lines.push('  OK    ' + label); }
  function bad(label) { lines.push('  MISS  ' + label); problems++; }
  function note(label) { lines.push('        ' + label); }

  lines.push('SHEET');
  try {
    var ss = ss_();
    lines.push('  OK    ' + ss.getName());
    [TAB_LISTINGS, TAB_SKUS, TAB_LOG, TAB_USERS].forEach(function (tab) {
      ss.getSheetByName(tab) ? ok('tab ' + tab) : bad('tab ' + tab + ' — run setupSheets()');
    });
  } catch (e) {
    bad('cannot open the data sheet: ' + e.message);
    note('check DRIVE_ROOT_ID / DATA_SHEET_ID in Config.gs, and that you have access');
  }

  lines.push('');
  lines.push('PEOPLE');
  try {
    var users = readAll_(TAB_USERS);
    var owner = users.filter(function (u) {
      return String(u.email).toLowerCase() === OWNER_EMAIL.toLowerCase();
    })[0];
    if (owner && String(owner.role).toLowerCase() === ROLE_ADMIN) {
      ok(OWNER_EMAIL + ' is admin');
    } else {
      bad(OWNER_EMAIL + ' is not admin — run setupSheets()');
    }
    var listers = users.filter(function (u) {
      var r = String(u.role).toLowerCase();
      return r === ROLE_ADMIN || r === ROLE_LISTER;
    }).length;
    note(listers + ' account(s) can list, ' + users.length + ' signed in so far');
  } catch (e) {
    bad('cannot read the Users tab: ' + e.message);
  }

  // The single most misconfigured value in this whole setup, and the one with
  // the least helpful failure: TikTok redirects to whatever Partner Center has
  // registered, and if that is a deployment id which no longer exists, Google
  // answers with "Sorry, unable to open the file at present" — a Drive error
  // page that says nothing about TikTok, Apps Script or deployments. Printing
  // the live URL turns that into a two-string comparison.
  lines.push('');
  lines.push('CALLBACK URL — must match Partner Center exactly, for every shop');
  try {
    var execUrl = ScriptApp.getService().getUrl();
    if (execUrl) {
      ok(execUrl);
      note('  Partner Center > your app > Redirect URL. One character off and');
      note('  authorising fails with a Google Drive error that mentions none of this.');
      note('  It changes ONLY if you make a new DEPLOYMENT; a new version keeps it.');
    } else {
      bad('no deployment URL — deploy this project as a web app first');
    }
  } catch (e) {
    bad('could not read the deployment URL: ' + e.message);
  }

  lines.push('');
  lines.push('GOOGLE SIGN-IN');
  // Presence is not the useful question — a client id that is present but
  // wrong refuses every sign-in just as completely as one that is missing,
  // and looks fine in a list of properties. So print it and check its shape.
  // It is not a secret: it ships inside the app's public JavaScript.
  var clientId = prop_('GOOGLE_CLIENT_ID');
  if (!clientId) {
    bad('GOOGLE_CLIENT_ID — not set, so nobody can sign in');
    note('  add it here: Project Settings (gear, left) > Script Properties > Add');
    note('  it is the SAME value as VITE_GOOGLE_CLIENT_ID in Netlify, and ends');
    note('  in .apps.googleusercontent.com');
  } else if (clientId.indexOf('.apps.googleusercontent.com') === -1) {
    bad('GOOGLE_CLIENT_ID does not end in .apps.googleusercontent.com: ' + clientId);
    note('  that is probably the client SECRET or a project number, not the client ID');
  } else {
    ok('GOOGLE_CLIENT_ID = ' + clientId);
    note('  this must match VITE_GOOGLE_CLIENT_ID in Netlify exactly');
  }

  SHOPS.forEach(function (shop) {
    lines.push('');
    lines.push(shop.brand + '  (' + shop.id + ')');

    var creds = ['APP_KEY', 'APP_SECRET', 'SERVICE_ID'];
    var present = creds.filter(function (k) { return Boolean(prop_(shop.id + '_' + k)); });

    // A shop with nothing entered has not been started; a shop with some of
    // three has been started and got stuck. Those are different situations and
    // the second is the alarming one, so they do not read the same. Counting a
    // deliberately deferred shop as three separate faults buries the ones that
    // actually block a livestream.
    if (present.length === 0) {
      note('not set up yet — nothing entered for this shop');
      note('  skip this if you are not using it yet; otherwise Partner Center, ' +
           'on this shop\'s own custom app');
      return;
    }

    creds.forEach(function (k) {
      prop_(shop.id + '_' + k)
        ? ok(shop.id + '_' + k + ' set')
        : bad(shop.id + '_' + k + ' — the other ' + (present.length) + ' are set, so this one is a gap');
    });
    if (present.length < creds.length) {
      note('from Partner Center, on this shop\'s own custom app');
      return;
    }

    // Tokens, and how long they have left. A shop whose refresh token has
    // lapsed can only be recovered by authorising again, so the warning has to
    // come before it happens rather than after. TikTok gives both expiries as
    // absolute epoch SECONDS, not durations.
    var expiry = Number(prop_(shop.id + '_REFRESH_EXPIRES') || 0);
    if (!prop_(shop.id + '_ACCESS_TOKEN')) {
      bad('not authorised — run ' + shop.authorizeFn + ' from the function dropdown');
      return;
    }
    ok('authorised');
    if (expiry) {
      var days = Math.floor((expiry * 1000 - Date.now()) / 86400000);
      days > 14 ? note('re-authorisation due in ' + days + ' days')
                : bad('re-authorise within ' + days + ' days');
    }

    // Also worth surfacing: the shop_cipher, which nearly every call needs.
    prop_(shop.id + '_SHOP_CIPHER')
      ? ok('shop_cipher stored')
      : bad('no shop_cipher — re-run ' + shop.authorizeFn);

    // The two calls that actually have to work before a livestream.
    try {
      var shops = ttAuthorizedShops_(shop.id, ttToken_(shop.id));
      shops.code === 0 ? ok('TikTok answers') : bad('TikTok: ' + shops.message);
    } catch (e) {
      bad('TikTok call failed: ' + e.message);
      return;
    }
    try {
      ttWarehouseId_(shop.id);
      ok('sales warehouse found');
    } catch (e) {
      // Not the same as the RETURN warehouse, which has no API at all — but a
      // missing sales warehouse fails every listing, so it is worth catching here.
      bad(e.message);
    }
  });

  lines.push('');
  lines.push('NOT CHECKABLE FROM HERE');
  note('Return warehouse per shop — Seller Center only, no API. Error 12052535');
  note('ANTHROPIC_API_KEY / GEMINI_API_KEY — those live on Netlify, not here');

  lines.push('');
  lines.push(problems === 0
    ? 'READY. Nothing missing.'
    : problems + ' thing(s) to fix. Each is marked MISS above.');

  var report = lines.join('\n');
  Logger.log(report);
  return report;
}


// ================================================================= Lock.gs

/**
 * One script lock, taken once per execution.
 *
 * Why this file exists
 * --------------------
 * Several layers of this backend each want to serialise: the API router wraps
 * every write action, `appendRows_` guards a Sheet append, `touchLastSeen_`
 * guards a cell update, and adding a variation to a TikTok product is a
 * read-modify-write that must not interleave. Left alone, they nest — the
 * router takes the lock, then `recordSku_` tries to take it again inside the
 * same execution.
 *
 * Whether that nesting is harmless depends on whether Apps Script's script
 * lock is re-entrant within a single execution, and the documentation does not
 * say. If it is not, `waitLock(30000)` inside a held lock blocks for the full
 * thirty seconds and then throws — turning every single push into a timeout —
 * while `tryLock` returns false and silently skips the work it was guarding.
 * Both failures are the kind that only show up in production, under load, on
 * factory Wi-Fi.
 *
 * Rather than bet on a behaviour that cannot be verified from outside the
 * Apps Script runtime, this helper makes the question irrelevant: it tracks
 * whether the current execution already holds the lock and, if so, simply runs
 * the work. Correct under either semantics.
 *
 * The flag is safe because Apps Script gives each execution its own global
 * scope and runs it single-threaded, so `HELD_` can never be observed by a
 * different request.
 */

/** True while this execution holds the script lock. Never shared across executions. */
var HELD_ = false;

/** How long to wait for the lock before giving up. */
var LOCK_TIMEOUT_MS = 30000;

/**
 * Run `fn` holding the script lock, taking it only if this execution does not
 * already hold it.
 *
 * @param {number} timeoutMs how long to wait; defaults to LOCK_TIMEOUT_MS
 * @param {function} fn the work to run
 * @throws Error prefixed 'BUSY:' when the lock cannot be taken, which the API
 *   router turns into a retryable response rather than a failure
 */
function withScriptLock_(timeoutMs, fn) {
  // Already ours. Re-taking it is exactly the nesting this file exists to
  // avoid, and the work is already serialised by the outer holder.
  if (HELD_) return fn();

  var lock = LockService.getScriptLock();
  if (!lock.tryLock(timeoutMs || LOCK_TIMEOUT_MS)) {
    throw new Error(
      'BUSY: Another change is being saved right now. This will retry in a moment — ' +
      'nothing has been lost.'
    );
  }

  HELD_ = true;
  try {
    return fn();
  } finally {
    // Cleared before releasing, so a caller that somehow observes the lock as
    // free never also sees it as held.
    HELD_ = false;
    lock.releaseLock();
  }
}

/**
 * Run `fn` under the lock, but skip it entirely rather than fail if the lock
 * is unavailable.
 *
 * For genuinely optional writes — recording a last-seen timestamp — where
 * blocking a livestream push to record a nicety is the wrong trade.
 */
function withScriptLockOptional_(timeoutMs, fn) {
  if (HELD_) return fn();

  var lock = LockService.getScriptLock();
  if (!lock.tryLock(timeoutMs || 5000)) return undefined;

  HELD_ = true;
  try {
    return fn();
  } finally {
    HELD_ = false;
    lock.releaseLock();
  }
}

/** True when this execution holds the lock. Exposed for assertions and tests. */
function holdsScriptLock_() {
  return HELD_;
}


// ================================================================ Sheet.gs

/**
 * The Sheet as the data store.
 *
 * Tabs are created on demand, so a fresh spreadsheet needs no manual setup —
 * calling setupSheets() once, or just using the app, produces them.
 *
 * Every write goes through LockService. Two people adding SKUs seconds apart
 * during a livestream would otherwise both read the same last row and one
 * would overwrite the other, silently losing a SKU.
 */

function ss_() { return SpreadsheetApp.openById(DATA_SHEET_ID); }

var HEADERS = {};
HEADERS[TAB_LISTINGS] = ['listing_id', 'shop_id', 'brand', 'product_name', 'supplier', 'created_at'];
HEADERS[TAB_SKUS] = [
  'sku_id', 'listing_id', 'shop_id', 'brand', 'identifier', 'title', 'variant',
  'price', 'stock', 'weight_kg', 'dims_cm', 'tiktok_image_uri', 'photo_url',
  'category_id', 'status', 'error', 'tiktok_product_id', 'idempotency_key',
  'created_at', 'pushed_at', 'created_by'
];
HEADERS[TAB_LOG] = ['timestamp_sgt', 'actor', 'action', 'shop', 'detail', 'result'];
HEADERS[TAB_USERS] = ['email', 'name', 'role', 'first_seen', 'last_seen', 'approved_by', 'note'];

/** Create any missing tab, with a frozen, bold header row. */
function sheet_(name) {
  var ss = ss_();
  var sh = ss.getSheetByName(name);
  if (!sh) {
    sh = ss.insertSheet(name);
    var headers = HEADERS[name] || [];
    if (headers.length) {
      sh.getRange(1, 1, 1, headers.length).setValues([headers]).setFontWeight('bold');
      sh.setFrozenRows(1);
    }
    // Drop the default "Sheet1" once a real tab exists, so the file does not
    // open on an empty sheet.
    var first = ss.getSheetByName('Sheet1');
    if (first && ss.getSheets().length > 1) ss.deleteSheet(first);
  }
  return sh;
}

/** Run once to lay the spreadsheet out. Safe to re-run. */
function setupSheets() {
  [TAB_LISTINGS, TAB_SKUS, TAB_LOG, TAB_USERS].forEach(function (n) { sheet_(n); });
  ensureOwner_();
  logEvent_('system', 'setup_sheets', '', 'Tabs ensured', 'ok');
  return 'Sheets ready: ' + ss_().getUrl();
}

/**
 * Append rows under the script lock, so concurrent writers cannot clobber
 * each other.
 *
 * Goes through withScriptLock_ rather than taking the lock directly, because
 * this is almost always called from inside a write action that already holds
 * it — see Lock.gs for why nesting the lock is a trap.
 */
function appendRows_(name, rows) {
  if (!rows.length) return;
  withScriptLock_(30000, function () {
    var sh = sheet_(name);
    sh.getRange(sh.getLastRow() + 1, 1, rows.length, rows[0].length).setValues(rows);
    SpreadsheetApp.flush();
  });
}

function readAll_(name) {
  var sh = sheet_(name);
  var last = sh.getLastRow();
  if (last < 2) return [];
  var headers = HEADERS[name];
  var values = sh.getRange(2, 1, last - 1, headers.length).getValues();
  return values.map(function (row) {
    var o = {};
    headers.forEach(function (h, i) { o[h] = row[i]; });
    return o;
  });
}

/**
 * The activity log.
 *
 * Brien asked for a record of what is happening. Every action lands here with
 * who did it, so "who listed this, and when" has an answer — the app being
 * replaced had no notion of a user at all.
 */
function logEvent_(actor, action, shop, detail, result) {
  try {
    appendRows_(TAB_LOG, [[
      Utilities.formatDate(new Date(), 'Asia/Singapore', 'yyyy-MM-dd HH:mm:ss'),
      actor || 'unknown',
      action,
      shop || '',
      String(detail || '').slice(0, 500),
      result || ''
    ]]);
  } catch (e) {
    // Logging must never break the thing it is logging.
    console.error('log failed: ' + e);
  }
}

// ── listings ─────────────────────────────────────────────────────────
function listListings_(shopId) {
  return readAll_(TAB_LISTINGS)
    .filter(function (r) { return String(r.shop_id) === String(shopId); })
    .sort(function (a, b) { return String(b.created_at).localeCompare(String(a.created_at)); });
}

function addListing_(shopId, listingId, actor) {
  var shop = shopById_(shopId);
  if (!shop) throw new Error('Unknown shop: ' + shopId);

  var existing = listListings_(shopId).filter(function (r) {
    return String(r.listing_id) === String(listingId);
  })[0];
  if (existing) return existing;

  var row = {
    listing_id: String(listingId),
    shop_id: shopId,
    brand: shop.brand,
    product_name: '',
    supplier: '',
    created_at: new Date().toISOString()
  };
  appendRows_(TAB_LISTINGS, [HEADERS[TAB_LISTINGS].map(function (h) { return row[h]; })]);
  logEvent_(actor, 'add_listing', shop.brand, 'listing ' + listingId, 'ok');
  return row;
}

// ── SKUs ─────────────────────────────────────────────────────────────
function listSkus_(listingId) {
  return readAll_(TAB_SKUS).filter(function (r) {
    return String(r.listing_id) === String(listingId);
  });
}

/** Already-pushed SKUs today, for the daily allowance figure. */
function pushedToday_(shopId) {
  var today = Utilities.formatDate(new Date(), 'Asia/Singapore', 'yyyy-MM-dd');
  return readAll_(TAB_SKUS).filter(function (r) {
    return String(r.shop_id) === String(shopId) &&
      String(r.status) === 'pushed' &&
      String(r.pushed_at).indexOf(today) === 0;
  }).length;
}

/** A prior push with this idempotency key, so a retry cannot duplicate. */
function findByIdempotencyKey_(key) {
  return readAll_(TAB_SKUS).filter(function (r) {
    return String(r.idempotency_key) === String(key) && String(r.status) === 'pushed';
  })[0] || null;
}

function recordSku_(sku) {
  var row = HEADERS[TAB_SKUS].map(function (h) { return sku[h] === undefined ? '' : sku[h]; });
  appendRows_(TAB_SKUS, [row]);
}


// ================================================================= Auth.gs

/**
 * Who is allowed to do what.
 *
 * Anyone with a Google account can sign in — that is deliberate, and it is
 * also how work gets attributed, since files are named after the person who
 * created them.
 *
 * But signing in is not permission to act. This app pushes products to live
 * TikTok shops, so a stranger who finds the URL must not be able to list
 * anything. A first-time signer is recorded as `pending` and can do nothing
 * until an admin changes their role in the Users tab.
 *
 * The allowlist lives in the Sheet on purpose: Brien can edit it himself,
 * without a deploy and without asking anyone.
 */

/** The signed-in Google account, or '' when the web app is open anonymously. */
function currentEmail_() {
  // getActiveUser() is populated for accounts in the same domain; for other
  // Google accounts getEffectiveUser() is the deploying user, so it is NOT a
  // safe identity source. The frontend therefore sends a verified Google ID
  // token, which is what verifyIdToken_ checks.
  try {
    return Session.getActiveUser().getEmail() || '';
  } catch (e) {
    return '';
  }
}

/**
 * Verify a Google ID token and return the identity it proves.
 *
 * The frontend signs the user in with Google and forwards the ID token. It is
 * verified against Google's tokeninfo endpoint rather than decoded locally, so
 * a forged token cannot pass — decoding a JWT without checking its signature
 * would make the whole allowlist decorative.
 */
function verifyIdToken_(idToken) {
  if (!idToken) {
    return refuse_('NO_TOKEN', 'Sign in with Google to continue.');
  }

  var res;
  try {
    res = UrlFetchApp.fetch(
      'https://oauth2.googleapis.com/tokeninfo?id_token=' + encodeURIComponent(idToken),
      { muteHttpExceptions: true }
    );
  } catch (e) {
    // Google unreachable is not the caller's fault, and telling them to sign
    // in again sends them round a loop that cannot terminate.
    return refuse_('GOOGLE_UNREACHABLE',
      'Could not reach Google to check your sign-in. Try again in a moment.');
  }

  if (res.getResponseCode() !== 200) {
    return refuse_('TOKEN_REJECTED',
      'Your Google sign-in has expired. Sign in again.');
  }

  var info;
  try {
    info = JSON.parse(res.getContentText());
  } catch (e) {
    return refuse_('TOKEN_UNREADABLE', 'Google returned a sign-in we could not read.');
  }

  // The token must have been issued for OUR client.
  //
  // This check fails CLOSED. It used to be skipped when GOOGLE_CLIENT_ID was
  // unset, which meant a half-configured deployment accepted a Google ID token
  // from any app on the internet — anyone could mint one against their own
  // client and be treated as a signed-in user. A backend that cannot say who
  // it is must refuse everyone, not everyone's token.
  //
  // Both refusals below name the configuration, because the alternative is a
  // sign-in screen that loops with no way to tell why. Neither leaks anything:
  // a client id is published inside the app's own JavaScript, and the message
  // says nothing about the person holding the token.
  var expectedClient = prop_('GOOGLE_CLIENT_ID');
  if (!expectedClient) {
    return refuse_('BACKEND_NOT_CONFIGURED',
      'This backend cannot verify sign-ins yet: GOOGLE_CLIENT_ID is not set in ' +
      'the Apps Script project settings. Nothing you can fix from here.');
  }
  if (info.aud !== expectedClient) {
    return refuse_('CLIENT_ID_MISMATCH',
      'Signed in with Google, but this backend is configured for a different ' +
      'Google client. The app signed you in as ' + shortClient_(info.aud) +
      ' and the backend expects ' + shortClient_(expectedClient) + '. ' +
      'Run checkSetup for the exact values.');
  }

  if (!info.email) {
    return refuse_('NO_EMAIL', 'That Google account did not return an email address.');
  }
  // Google sends this as the string "false", not a boolean.
  if (String(info.email_verified) === 'false') {
    return refuse_('EMAIL_UNVERIFIED', 'That Google account has an unverified email address.');
  }

  return {
    ok: true,
    email: String(info.email).toLowerCase(),
    name: info.name || info.email
  };
}

/** A refusal carrying why, so the sign-in screen can say something useful. */
function refuse_(code, message) {
  return { ok: false, code: code, message: message };
}

/**
 * Enough of a client id to compare two by eye, without a wall of base64.
 * These are not secrets — they ship in the frontend — but the full string is
 * 72 characters and unreadable on a phone.
 */
function shortClient_(id) {
  var s = String(id || '');
  if (!s) return '(none)';
  var dash = s.indexOf('-');
  return dash === -1 ? s.slice(0, 12) + '…' : s.slice(0, dash + 7) + '…';
}

function usersAll_() { return readAll_(TAB_USERS); }

function findUser_(email) {
  var target = String(email || '').toLowerCase();
  return usersAll_().filter(function (u) {
    return String(u.email).toLowerCase() === target;
  })[0] || null;
}

/** Seed the owner as admin, so there is always someone who can approve. */
function ensureOwner_() {
  if (findUser_(OWNER_EMAIL)) return;
  appendRows_(TAB_USERS, [[
    OWNER_EMAIL, 'Brien Chua', ROLE_ADMIN,
    new Date().toISOString(), '', 'system', 'Seeded owner'
  ]]);
}

/**
 * Resolve an identity to a user record, registering a newcomer as pending.
 *
 * Registering rather than rejecting outright is what makes approval possible:
 * Brien sees the person appear in the Users tab and flips their role, instead
 * of having to be told an email address out of band.
 */
function resolveUser_(identity) {
  ensureOwner_();
  var found = findUser_(identity.email);

  if (!found) {
    appendRows_(TAB_USERS, [[
      identity.email, identity.name, ROLE_PENDING,
      new Date().toISOString(), new Date().toISOString(), '', 'Awaiting approval'
    ]]);
    logEvent_(identity.email, 'first_sign_in', '', identity.name + ' — awaiting approval', 'pending');
    return { email: identity.email, name: identity.name, role: ROLE_PENDING };
  }

  touchLastSeen_(identity.email);
  return {
    email: String(found.email).toLowerCase(),
    name: found.name || identity.name,
    role: String(found.role || ROLE_PENDING).toLowerCase()
  };
}

function touchLastSeen_(email) {
  // Best effort: skipped rather than blocking a livestream push to record a
  // timestamp. See Lock.gs for why this does not take the lock directly.
  withScriptLockOptional_(5000, function () {
    var sh = sheet_(TAB_USERS);
    var last = sh.getLastRow();
    if (last < 2) return;
    var emails = sh.getRange(2, 1, last - 1, 1).getValues();
    var target = String(email).toLowerCase();
    for (var i = 0; i < emails.length; i++) {
      if (String(emails[i][0]).toLowerCase() === target) {
        sh.getRange(i + 2, 5).setValue(new Date().toISOString());
        return;
      }
    }
  });
}

function canList_(user) {
  return user && (user.role === ROLE_ADMIN || user.role === ROLE_LISTER);
}

function isAdmin_(user) {
  return user && user.role === ROLE_ADMIN;
}

/**
 * A filename-safe version of a person's name.
 *
 * Files are saved under the creator's name, so this has to cope with whatever
 * a Google profile contains — accents, punctuation, unusual spacing.
 */
function safeName_(name) {
  return String(name || 'unknown')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, ' ')
    .slice(0, 60) || 'unknown';
}


// =============================================================== TikTok.gs

/**
 * TikTok Shop integration.
 *
 * The signing algorithm and token handling follow the same shape as
 * Sheldon Delivery API, which has been running them in production. Two
 * independent implementations of this signer agreed step for step, which is
 * the best evidence available that it is right.
 *
 * Script Properties per shop, {P} being HZ | TM | PM:
 *   {P}_APP_KEY, {P}_APP_SECRET, {P}_SERVICE_ID   (set by hand once)
 *   {P}_ACCESS_TOKEN, {P}_ACCESS_EXPIRES,
 *   {P}_REFRESH_TOKEN, {P}_REFRESH_EXPIRES,
 *   {P}_SHOP_CIPHER                                (written by the callback)
 */

function ttCreds_(prefix) {
  var key = prop_(prefix + '_APP_KEY');
  var secret = prop_(prefix + '_APP_SECRET');
  if (!key || !secret) {
    throw new Error('No app credentials for ' + prefix +
      '. Add ' + prefix + '_APP_KEY and ' + prefix + '_APP_SECRET in Script Properties.');
  }
  return { key: key, secret: secret };
}

/**
 * Request signature.
 *
 * Sort the query minus sign/access_token, join as key+value with NO
 * separators, prefix the path, append the exact body string (skipped for
 * multipart), wrap in the app secret, HMAC-SHA256, lowercase hex.
 */
function ttSign_(path, query, bodyString, secret) {
  var keys = Object.keys(query).filter(function (k) {
    return k !== 'sign' && k !== 'access_token';
  }).sort();
  var input = path;
  keys.forEach(function (k) { input += k + query[k]; });
  if (bodyString) input += bodyString;
  var raw = Utilities.computeHmacSha256Signature(secret + input + secret, secret);
  return raw.map(function (b) { return ('0' + (b & 0xff).toString(16)).slice(-2); }).join('');
}

function ttQuery_(q) {
  return Object.keys(q).map(function (k) {
    return encodeURIComponent(k) + '=' + encodeURIComponent(q[k]);
  }).join('&');
}

/**
 * Consent URL for one shop.
 *
 * The service_id identifies the APP the seller is being asked to authorise, and
 * it is generated per app registration — so it is not interchangeable with the
 * one in Sheldon Delivery API. Reusing that one would send the seller to
 * authorise the delivery app, and TikTok would then redirect to the delivery
 * project's callback, not this one: the tokens would land in the wrong place
 * and this project would simply never receive them.
 *
 * Find it in Partner Center on the app's own page, alongside the App Key and
 * App Secret. If the label is not obvious, open the authorisation link Partner
 * Center generates for the app — the number after `service_id=` is it.
 */
function ttAuthorizeUrl(prefix) {
  var serviceId = prop_(prefix + '_SERVICE_ID');
  if (!serviceId) {
    throw new Error(
      'Set ' + prefix + '_SERVICE_ID in Script Properties first.\n\n' +
      'It comes from THIS project\'s ' + prefix + ' app in TikTok Partner Center — ' +
      'next to the App Key and App Secret, or as the number after "service_id=" in ' +
      'the authorisation link Partner Center shows for that app.\n\n' +
      'Do NOT copy it from Sheldon Delivery API. That is a different app ' +
      'registration, and its callback points at the delivery project — the ' +
      'tokens would never arrive here.'
    );
  }
  return 'https://services.tiktokshop.com/open/authorize?service_id=' +
    encodeURIComponent(serviceId) + '&state=' + encodeURIComponent(prefix);
}

/**
 * Zero-argument wrappers, one per shop.
 *
 * The Apps Script editor's Run button cannot pass arguments, so calling
 * ttAuthorizeUrl('HZ') from the toolbar is not possible — you would have to
 * edit the source to change the shop, which is exactly the kind of fiddling
 * that gets done wrong at speed. Three named functions make the dropdown the
 * whole interface.
 *
 * Each logs a consent URL. Open it in a browser signed in to THAT shop's
 * TikTok account, ideally a private window per shop so the sessions do not
 * collide.
 */
function authorizeHOUZE() { return logAuthorizeUrl_('HZ'); }
function authorizeTableMatters() { return logAuthorizeUrl_('TM'); }
function authorizePaintingMatters() { return logAuthorizeUrl_('PM'); }

/**
 * Every shop that still needs authorising, in one run.
 *
 * Authorising is the one step in this whole setup that cannot be automated —
 * it is a consent screen that has to be approved while signed in as the shop.
 * So the least this can do is stop making someone run a different function per
 * shop, work out which ones are outstanding, and re-read the log each time.
 *
 * Shops already authorised are skipped rather than re-listed, because a
 * re-authorisation that was not wanted costs the tokens currently working.
 * Shops with no credentials are skipped too — Table Matters is deliberately
 * not set up, and printing a broken link for it every run trains people to
 * ignore the output.
 */
function authorizeAll() {
  var lines = ['', 'SHOPS TO AUTHORISE', ''];
  var pending = 0;

  SHOPS.forEach(function (shop) {
    if (!prop_(shop.id + '_SERVICE_ID')) {
      lines.push('- ' + shop.brand + ': skipped, not set up yet');
      return;
    }
    if (prop_(shop.id + '_ACCESS_TOKEN')) {
      lines.push('- ' + shop.brand + ': already authorised, nothing to do');
      return;
    }
    pending++;
    lines.push('');
    lines.push('== ' + pending + '. ' + shop.brand + '  (' + shop.handle + ') ==');
    lines.push('Open this signed in as ' + shop.handle + ', in a PRIVATE window:');
    lines.push('');
    lines.push('   ' + ttAuthorizeUrl(shop.id));
    lines.push('');
  });

  lines.push('');
  if (pending === 0) {
    lines.push('Nothing to authorise. Run checkSetup to confirm the rest.');
  } else {
    // Printed here rather than only in checkSetup, because this is the moment
    // it matters. TikTok redirects to whatever Partner Center has registered,
    // and a stale deployment id there fails as a Google Drive page reading
    // "Sorry, unable to open the file at present" — which names nothing that
    // would lead you back to this setting.
    try {
      var execUrl = ScriptApp.getService().getUrl();
      if (execUrl) {
        lines.push('BEFORE YOU CLICK: each app\'s Redirect URL in Partner Center');
        lines.push('must be EXACTLY this, or approving lands on a Google Drive error:');
        lines.push('');
        lines.push('   ' + execUrl);
        lines.push('');
      }
    } catch (e) { /* not deployed yet; checkSetup reports that properly */ }

    lines.push(pending + ' shop(s) to go.');
    lines.push('A private window per shop, or the second sign-in reuses the first.');
    lines.push('After approving, TikTok returns you to this script and stores the');
    lines.push('tokens. Then run checkSetup.');
  }

  var out = lines.join('\n');
  Logger.log(out);
  return out;
}

function logAuthorizeUrl_(prefix) {
  var shop = shopById_(prefix);
  var url = ttAuthorizeUrl(prefix);
  Logger.log(
    'Authorise ' + (shop ? shop.brand : prefix) + ' (' + prefix + ')\n\n' + url +
    '\n\nOpen that while signed in to ' + (shop ? shop.handle : 'the right shop') +
    '. A private window avoids clashing with another shop\'s session.'
  );
  return url;
}

/**
 * The OAuth callback. `state` carries which shop began the flow — with three
 * shops, guessing would file one brand's tokens against another.
 */
function ttHandleAuthCallback_(e) {
  var code = e.parameter.code;
  var prefix = String(e.parameter.state || '').toUpperCase();
  if (!shopById_(prefix)) {
    return HtmlService.createHtmlOutput('<p>Unknown shop in callback state.</p>');
  }
  try {
    var c = ttCreds_(prefix);
    var url = TT_AUTH_HOST + '/api/v2/token/get?' + ttQuery_({
      app_key: c.key, app_secret: c.secret, auth_code: code,
      // Not the OAuth-standard 'authorization_code'. TikTok deviates here and
      // the standard spelling fails.
      grant_type: 'authorized_code'
    });
    var body = JSON.parse(UrlFetchApp.fetch(url, { muteHttpExceptions: true }).getContentText() || '{}');
    if (body.code !== 0) throw new Error(body.message || 'token exchange failed');

    var d = body.data;
    var set = {};
    set[prefix + '_ACCESS_TOKEN'] = d.access_token;
    set[prefix + '_ACCESS_EXPIRES'] = String(d.access_token_expire_in || 0);
    set[prefix + '_REFRESH_TOKEN'] = d.refresh_token;
    set[prefix + '_REFRESH_EXPIRES'] = String(d.refresh_token_expire_in || 0);
    setProps_(set);

    // Ask TikTok which shops the token covers, and keep the cipher. Never
    // hardcode it — the docs say so explicitly.
    var shops = ttAuthorizedShops_(prefix, d.access_token);
    if (shops.code === 0 && shops.data && shops.data.shops && shops.data.shops.length) {
      var s = {};
      s[prefix + '_SHOP_CIPHER'] = shops.data.shops[0].cipher;
      s[prefix + '_SHOP_ID'] = shops.data.shops[0].id;
      setProps_(s);
    }

    logEvent_('system', 'tiktok_authorised', shopById_(prefix).brand, prefix, 'ok');
    return HtmlService.createHtmlOutput(
      '<p>' + shopById_(prefix).brand + ' connected. You can close this window.</p>'
    );
  } catch (err) {
    logEvent_('system', 'tiktok_authorise_failed', prefix, String(err), 'error');
    return HtmlService.createHtmlOutput('<p>Could not connect: ' + err + '</p>');
  }
}

/** Refresh, storing BOTH tokens — TikTok issues a new refresh token too. */
function ttRefresh_(prefix) {
  var c = ttCreds_(prefix);
  var rt = prop_(prefix + '_REFRESH_TOKEN');
  if (!rt) throw new Error(prefix + ' is not authorised yet.');
  var url = TT_AUTH_HOST + '/api/v2/token/refresh?' + ttQuery_({
    app_key: c.key, app_secret: c.secret, refresh_token: rt, grant_type: 'refresh_token'
  });
  var body = JSON.parse(UrlFetchApp.fetch(url, { muteHttpExceptions: true }).getContentText() || '{}');
  if (body.code !== 0) throw new Error(prefix + ' refresh failed: ' + body.message);
  var d = body.data, set = {};
  set[prefix + '_ACCESS_TOKEN'] = d.access_token;
  set[prefix + '_ACCESS_EXPIRES'] = String(d.access_token_expire_in || 0);
  if (d.refresh_token) {
    set[prefix + '_REFRESH_TOKEN'] = d.refresh_token;
    set[prefix + '_REFRESH_EXPIRES'] = String(d.refresh_token_expire_in || 0);
  }
  setProps_(set);
  return d.access_token;
}

/** A live access token, refreshed inside 24h of expiry. */
function ttToken_(prefix) {
  var tok = prop_(prefix + '_ACCESS_TOKEN');
  var exp = Number(prop_(prefix + '_ACCESS_EXPIRES') || 0);
  if (!tok) throw new Error(shopById_(prefix).brand + ' is not connected to TikTok yet.');
  // Refresh early: discovering an expired token mid-livestream is the
  // expensive case.
  if (exp && exp - Math.floor(Date.now() / 1000) < 86400) return ttRefresh_(prefix);
  return tok;
}

/** Signed call. `payload` is an object (JSON) or a Blob (multipart). */
function ttFetch_(prefix, method, path, extraQuery, payload) {
  var c = ttCreds_(prefix);
  var token = ttToken_(prefix);
  var cipher = prop_(prefix + '_SHOP_CIPHER');

  var query = { app_key: c.key, timestamp: String(Math.floor(Date.now() / 1000)) };
  if (cipher) query.shop_cipher = cipher;
  Object.keys(extraQuery || {}).forEach(function (k) { query[k] = extraQuery[k]; });

  var isBlob = payload && typeof payload.getBytes === 'function';
  // Stringified ONCE, and that exact string is both signed and sent.
  var bodyString = (payload && !isBlob) ? JSON.stringify(payload) : '';
  query.sign = ttSign_(path, query, bodyString, c.secret);

  var opts = { method: method, muteHttpExceptions: true,
               headers: { 'x-tts-access-token': token } };
  if (isBlob) {
    opts.payload = { data: payload };  // multipart; body is not signed
  } else if (bodyString) {
    opts.contentType = 'application/json';
    opts.payload = bodyString;
  }

  var url = TT_HOST + path + '?' + ttQuery_(query);
  var res = UrlFetchApp.fetch(url, opts);
  var parsed = ttParse_(res);

  // Throttling is HTTP 429 or business code 36009002. At three shops we sit
  // near one write per second, so one backoff is worth it.
  if (res.getResponseCode() === 429 || parsed.code === 36009002) {
    Utilities.sleep(5000);
    parsed = ttParse_(UrlFetchApp.fetch(url, opts));
  }
  return parsed;
}

function ttParse_(res) {
  var txt = res.getContentText() || '';
  try { return JSON.parse(txt); }
  catch (e) { return { code: -1, message: 'Non-JSON response: ' + txt.slice(0, 200) }; }
}

function ttAuthorizedShops_(prefix, accessToken) {
  var c = ttCreds_(prefix);
  var path = '/authorization/202309/shops';
  var query = { app_key: c.key, timestamp: String(Math.floor(Date.now() / 1000)) };
  query.sign = ttSign_(path, query, '', c.secret);
  return ttParse_(UrlFetchApp.fetch(TT_HOST + path + '?' + ttQuery_(query), {
    method: 'get', muteHttpExceptions: true,
    headers: { 'x-tts-access-token': accessToken }
  }));
}

/** Check every shop answers. Run by hand after setting up credentials. */
function ttSelfTest() {
  var out = [];
  SHOPS.forEach(function (s) {
    try {
      var r = ttAuthorizedShops_(s.id, ttToken_(s.id));
      out.push(s.brand + ': ' + (r.code === 0 ? 'OK' : 'code ' + r.code + ' ' + r.message));
    } catch (e) {
      out.push(s.brand + ': ' + e.message);
    }
  });
  var report = out.join('\n');
  Logger.log(report);
  return report;
}


// ============================================================== Product.gs

/**
 * Listing a product on TikTok.
 *
 * Order of operations matters — it is what avoids the two commonest failures:
 *   1. resolve a LEAF category (products cannot be created in a branch),
 *   2. fetch that category's mandatory attributes and fill them,
 *   3. dry-run with listing_check, so problems are named before they cost a
 *      slot against the daily upload cap,
 *   4. create.
 */

/** English-only, 25-255 characters. Both are TikTok's rules for Singapore. */
function validateTitle_(title) {
  var t = String(title || '').trim();
  if (!t) return 'Title is required.';
  if (t.length < TITLE_MIN) {
    return 'Title must be at least ' + TITLE_MIN + ' characters for Singapore — this is ' +
      t.length + '. TikTok rejects anything shorter.';
  }
  if (t.length > TITLE_MAX) return 'Title must be at most ' + TITLE_MAX + ' characters.';
  // ASCII control characters, including DEL. Checked before the English rule
  // so the message names the actual problem — the rule below would also catch
  // these, but would report them as "not English", which sends someone looking
  // for a Chinese character that is not there.
  if (/[\u0000-\u001F\u007F]/.test(t)) return 'Title contains control characters.';
  // HTML entities such as &nbsp;. Forbidden by 12052931, and invisible to
  // every other rule here: the characters are all plain ASCII, so without this
  // check a title carrying one is accepted locally and refused by TikTok.
  if (/&(?:[a-zA-Z][a-zA-Z0-9]{1,31}|#\d{1,7}|#[xX][0-9a-fA-F]{1,6});/.test(t)) {
    return 'Title contains an HTML entity such as &nbsp; — write the character itself.';
  }
  // Anything outside Latin-1 plus common punctuation: catches Chinese, which
  // TikTok refuses in product names, and emoji.
  if (/[^\u0020-\u024F\u2018\u2019\u201C\u201D\u2013\u2014]/.test(t)) {
    return 'Title must be English. TikTok rejects Chinese characters and emoji in product names.';
  }
  if (!/[a-zA-Z0-9]/.test(t)) return 'Title cannot be only symbols.';
  if (/(.)\1{9,}/.test(t)) return 'Title repeats one character more than nine times in a row.';
  return '';
}

/**
 * Upload a photo and return its TikTok uri.
 *
 * The use case matters and is not interchangeable. TikTok issues a separate
 * uri per use case and refuses one in the other's place:
 *
 *   MAIN_IMAGE       the product hero, used when a listing is created
 *   ATTRIBUTE_IMAGE  the photo shown against a variation in the buyer's
 *                    options gallery, which is where every SKU after the
 *                    first appears
 *
 * So the same JPEG is uploaded twice on the SKU that creates a listing.
 */
function ttUploadImage_(prefix, blob, useCase) {
  var r = ttFetch_(prefix, 'post', '/product/202309/images/upload',
    { use_case: useCase || 'MAIN_IMAGE' }, blob);
  if (r.code !== 0) throw new Error('Image upload failed: ' + (r.message || r.code));
  return r.data.uri;
}

/**
 * The buyer-visible name for a variation.
 *
 * Leads with the identifier on purpose: in a factory livestream the host says
 * "A7 is the blue one" and the buyer looks for A7 in the variant picker, so the
 * identifier is the shared vocabulary of the whole broadcast. Capped at
 * TikTok's 50 characters, at a word boundary where one is available.
 */
function variantValueName_(identifier, variantName) {
  var name = String(variantName || '').trim().replace(/\s+/g, ' ');
  var combined = name ? identifier + ' ' + name : String(identifier);
  if (combined.length <= VALUE_NAME_MAX) return combined;
  var clipped = combined.slice(0, VALUE_NAME_MAX);
  var lastSpace = clipped.lastIndexOf(' ');
  return lastSpace > VALUE_NAME_MAX * 0.6 ? clipped.slice(0, lastSpace) : clipped.replace(/\s+$/, '');
}

/**
 * Validate a variant name — the buyer-visible name of one variation.
 *
 * Deliberately NOT validateTitle_. A product title and a variant name are
 * different fields with different rules, and conflating them was a real bug:
 * a title floors at 25 characters and caps at 255, a variant name has no
 * minimum and caps at 50. So "Blue Mug" is perfectly valid here and was being
 * rejected.
 *
 * The character rules are shared, because TikTok polices them identically in
 * both places — 12052243 rejects Chinese in a sales-attribute name just as
 * 12052262 rejects it in a product name.
 */
function validateVariantName_(name) {
  var n = String(name || '').trim();
  if (!n) return 'Variant name is required.';
  if (n.length > VALUE_NAME_MAX) {
    return 'Variant name must be at most ' + VALUE_NAME_MAX + ' characters — this is ' +
      n.length + '.';
  }
  if (/[\u0000-\u001F\u007F]/.test(n)) return 'Variant name contains control characters.';
  if (/&(?:[a-zA-Z][a-zA-Z0-9]{1,31}|#\d{1,7}|#[xX][0-9a-fA-F]{1,6});/.test(n)) {
    return 'Variant name contains an HTML entity such as &nbsp; — write the character itself.';
  }
  if (/[^\u0020-\u024F\u2018\u2019\u201C\u201D\u2013\u2014]/.test(n)) {
    return 'Variant name must be English. TikTok rejects Chinese characters and emoji here.';
  }
  if (!/[a-zA-Z0-9]/.test(n)) return 'Variant name cannot be only symbols.';
  if (/(.)\1{9,}/.test(n)) {
    return 'Variant name repeats one character more than nine times in a row.';
  }
  return '';
}

/**
 * The title for a continuation listing.
 *
 * Singapore caps a product at 100 variations, so a long factory run spills
 * into a second listing. That listing needs a product title, and the one thing
 * it must not need is for someone to invent one mid-broadcast — so it is
 * derived from the listing it continues.
 *
 * An existing "(2)" is incremented rather than stacked, because a 300-SKU run
 * produces a third listing and "Ceramic Run (2) (2)" is nobody's idea of a
 * product name.
 */
function continuationTitle_(parentTitle) {
  var title = String(parentTitle || '').trim();
  var match = /^(.*?)\s*\((\d+)\)$/.exec(title);
  var base = match ? match[1].replace(/\s+$/, '') : title;
  var next = match ? parseInt(match[2], 10) + 1 : 2;
  var suffix = ' (' + next + ')';
  var room = TITLE_MAX - suffix.length;
  if (base.length > room) base = base.slice(0, room).replace(/\s+$/, '');
  return base + suffix;
}

/**
 * Read a product and its variations.
 *
 * Called immediately before every edit, and its result is the only safe basis
 * for one — see buildAppendPayload_ for why a cached snapshot is worse than
 * no snapshot at all.
 *
 * Note the price translation. Get Product returns `price.sale_price`; every
 * write endpoint takes `price.amount`. Reading one and writing the other
 * blanks the price of every existing variation, so it happens once, here.
 */
function ttGetProduct_(prefix, productId) {
  var r = ttFetch_(prefix, 'get', '/product/202309/products/' + productId,
    { category_version: CATEGORY_VERSION }, null);
  if (r.code !== 0 || !r.data) {
    throw new Error('Could not read the listing: ' + (r.message || r.code));
  }
  var skus = (r.data.skus || []).map(function (raw) {
    var attribute = (raw.sales_attributes || [])[0] || {};
    var inventory = (raw.inventory || [])[0] || {};
    return {
      id: raw.id || '',
      sellerSku: raw.seller_sku || '',
      attributeId: attribute.id || '',
      attributeName: attribute.name || '',
      valueId: attribute.value_id || '',
      valueName: attribute.value_name || '',
      skuImgUri: (attribute.sku_img && attribute.sku_img.uri) || '',
      priceAmount: String((raw.price && (raw.price.sale_price || raw.price.amount)) || ''),
      quantity: Number(inventory.quantity || 0),
      warehouseId: inventory.warehouse_id || ''
    };
  });
  return { productId: r.data.id || productId, title: r.data.title || '', skus: skus };
}

/**
 * Build the payload that adds a variation to an existing product.
 *
 * The single most dangerous fact about TikTok's edit API, quoted from the
 * Partial Edit Product reference:
 *
 *   "You must pass in all existing SKUs. Any existing SKU IDs not listed here
 *    will result in the deletion of those SKUs. For example, if this product
 *    contains 5 SKUs and you only provide 2 SKU IDs, the remaining 3 will be
 *    deleted."
 *
 * So there is no "append" call. Adding the 51st variation means sending all 51
 * — the 50 existing ones carrying their `id`, the new one with its `id` left
 * blank. Send only the new one and the livestream's entire back catalogue is
 * deleted, silently, with a success response.
 *
 * Throws 'LISTING_FULL' when the ceiling is reached, so the caller can offer a
 * continuation listing rather than reporting a failure.
 */
function buildAppendPayload_(snapshot, addition) {
  if (!snapshot.skus.length) {
    throw new Error('This listing has no variations to extend. TikTok requires at least one ' +
      'sales attribute on a product, so the first variation has to be created with the product.');
  }
  for (var i = 0; i < snapshot.skus.length; i++) {
    // Without an id we cannot say "keep this one", and TikTok would treat it as
    // a new SKU — duplicating it while deleting the original.
    if (!snapshot.skus[i].id) {
      throw new Error('TikTok returned a variation without an ID for this listing. Adding to ' +
        'it now would duplicate it, so nothing was sent. Try again in a moment.');
    }
    // 12052533: "Removal, addition, and change of warehouses are not
    // permitted. Please specify the original warehouses for the SKUs."
    if (!snapshot.skus[i].warehouseId) {
      throw new Error('TikTok did not return a warehouse for every existing variation. ' +
        'Editing this listing would drop their stock, so nothing was sent.');
    }
  }
  if (snapshot.skus.length + 1 > MAX_SKUS_PER_PRODUCT) {
    throw new Error('LISTING_FULL');
  }

  var first = snapshot.skus[0];
  // "Provide either a built-in ID or a custom name; if both are provided, the
  // ID takes priority." So sending our own name against an established id
  // would be silently ignored.
  var identity = first.attributeId
    ? { id: first.attributeId }
    : { name: first.attributeName || VARIANT_ATTRIBUTE_NAME };
  var warehouseId = first.warehouseId;

  var valueName = variantValueName_(addition.identifier, addition.variantName);
  var taken = {};
  var skus = snapshot.skus.map(function (sku) {
    if (sku.valueName) taken[String(sku.valueName).toLowerCase()] = true;
    var attribute = sku.attributeId ? { id: sku.attributeId }
                                    : { name: sku.attributeName || VARIANT_ATTRIBUTE_NAME };
    if (sku.valueId) {
      // Re-sending value_name for a value that already has an id would create
      // a second value rather than reference the existing one.
      attribute.value_id = sku.valueId;
    } else {
      attribute.value_name = sku.valueName;
    }
    // An image is mandatory for every value of the primary attribute, so
    // dropping one existing photo fails the whole edit.
    if (sku.skuImgUri) attribute.sku_img = { uri: sku.skuImgUri };
    return {
      id: sku.id,
      seller_sku: sku.sellerSku || undefined,
      price: { amount: sku.priceAmount, currency: CURRENCY },
      inventory: [{ warehouse_id: sku.warehouseId, quantity: sku.quantity }],
      sales_attributes: [attribute]
    };
  });

  // "No duplicates allowed under the same attribute." The identifier makes
  // this all but impossible, so hitting it means an identifier repeated.
  if (taken[valueName.toLowerCase()]) {
    throw new Error('A variation called "' + valueName + '" is already on this listing. ' +
      'Identifier ' + addition.identifier + ' looks to have been used twice.');
  }

  var added = {
    // No `id`: "To create new SKUs, leave the SKU ID blank and complete the
    // other fields."
    seller_sku: addition.identifier,
    price: { amount: String(addition.price), currency: CURRENCY },
    inventory: [{ warehouse_id: warehouseId, quantity: Number(addition.stock) }],
    sales_attributes: [{
      name: identity.name, id: identity.id,
      value_name: valueName,
      sku_img: { uri: addition.imageUri }
    }]
  };
  // Drop the undefined half of the identity so TikTok sees one or the other.
  if (!added.sales_attributes[0].id) delete added.sales_attributes[0].id;
  if (!added.sales_attributes[0].name) delete added.sales_attributes[0].name;
  skus.push(added);

  // Last line of defence. Everything above is meant to guarantee this, so a
  // failure here is a bug — but the cost of being wrong is a deleted
  // livestream, so it is checked anyway.
  var kept = {};
  skus.forEach(function (s) { if (s.id) kept[s.id] = true; });
  for (var j = 0; j < snapshot.skus.length; j++) {
    if (!kept[snapshot.skus[j].id]) {
      throw new Error('Refusing to edit: variation ' +
        (snapshot.skus[j].sellerSku || snapshot.skus[j].id) +
        ' would have been deleted. This is a bug — nothing was sent to TikTok.');
    }
  }

  return { skus: skus, category_version: CATEGORY_VERSION };
}

function ttRecommendCategory_(prefix, title, imageUri) {
  var r = ttFetch_(prefix, 'post', '/product/202309/categories/recommend', {}, {
    product_title: title,
    images: [{ uri: imageUri }],
    category_version: CATEGORY_VERSION
  });
  if (r.code !== 0 || !r.data || !r.data.leaf_category_id) {
    throw new Error('Could not resolve a category: ' + (r.message || r.code));
  }
  return r.data.leaf_category_id;
}

/**
 * Mandatory attributes for a category, filled with the first allowed value.
 *
 * NOTE the flag is `is_requried` — TikTok's own schema misspells it. Reading
 * `is_required` returns undefined, silently skips every required attribute,
 * and the listing then fails at create with an unhelpful error.
 *
 * Taking the first value is a deliberate simplification: these are fields like
 * "Material" that TikTok insists on but nobody wants to answer 200 times
 * mid-livestream, and they stay editable in Seller Center.
 */
function ttRequiredAttributes_(prefix, categoryId) {
  var r = ttFetch_(prefix, 'get',
    '/product/202309/categories/' + categoryId + '/attributes',
    { category_version: CATEGORY_VERSION }, null);
  if (r.code !== 0 || !r.data) return [];
  return (r.data.attributes || []).filter(function (a) {
    return a.type === 'PRODUCT_PROPERTY' && a.is_requried === true &&
      a.values && a.values.length;
  }).map(function (a) {
    return { id: a.id, values: [{ id: a.values[0].id }] };
  });
}

/** A sales warehouse id, required on every SKU's inventory. */
function ttWarehouseId_(prefix) {
  var cached = prop_(prefix + '_WAREHOUSE_ID');
  if (cached) return cached;
  var r = ttFetch_(prefix, 'get', '/logistics/202309/warehouses', {}, null);
  if (r.code !== 0) throw new Error('Could not read warehouses: ' + r.message);
  var usable = (r.data.warehouses || []).filter(function (w) {
    return w.type === 'SALES_WAREHOUSE' && w.effect_status === 'ENABLED';
  });
  var chosen = usable.filter(function (w) { return w.is_default; })[0] || usable[0];
  if (!chosen) {
    throw new Error('No enabled sales warehouse for this shop. Set one up in Seller Center first.');
  }
  var set = {}; set[prefix + '_WAREHOUSE_ID'] = chosen.id; setProps_(set);
  return chosen.id;
}

function buildPayload_(input, categoryId, warehouseId, attributes) {
  var payload = {
    title: input.title,
    // Mandatory, HTML, English. Derived from the title because nobody writes
    // a description mid-livestream.
    description: '<p>' + String(input.title).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') + '</p>',
    category_id: categoryId,
    category_version: CATEGORY_VERSION,
    main_images: [{ uri: input.imageUri }],
    package_weight: { value: input.weightKg || DEFAULT_WEIGHT_KG, unit: WEIGHT_UNIT },
    package_dimensions: {
      length: DEFAULT_DIMS.length, width: DEFAULT_DIMS.width,
      height: DEFAULT_DIMS.height, unit: DIMENSION_UNIT
    },
    skus: [{
      seller_sku: input.identifier,
      price: { amount: String(input.price), currency: CURRENCY },
      inventory: [{ warehouse_id: warehouseId, quantity: Number(input.stock) }],
      // The sales attribute every later variation joins. Named rather than
      // referenced by id, because a custom attribute has no id until TikTok
      // generates one on create.
      //
      // This is the step that makes the rest of the stream possible: a product
      // created without a sales attribute can never gain one, since "You must
      // retain at least 1 sales attribute" cuts both ways.
      sales_attributes: [{
        name: VARIANT_ATTRIBUTE_NAME,
        value_name: variantValueName_(input.identifier, input.variantName),
        sku_img: { uri: input.attributeImageUri || input.imageUri }
      }]
    }],
    save_mode: 'LISTING',
    // Makes a timed-out create safe to retry without duplicating the product.
    idempotency_key: input.idempotencyKey
  };
  if (attributes && attributes.length) payload.product_attributes = attributes;
  return payload;
}

/**
 * Push one SKU into a livestream.
 *
 * A factory stream is ONE TikTok product, and each SKU called out on air is a
 * *variation* of it. So the normal path is not "create a product", it is "add a
 * variation to the product this stream lists against". Creating a product
 * happens twice in a stream at most: once at the start, and again if the run
 * outgrows Singapore's 100-variation ceiling.
 *
 * Everything runs under the script lock. Adding a variation is a
 * read-modify-write of the product's whole SKU list, and two of those at once
 * is a lost update whose consequence is a *deleted* variation rather than an
 * overwritten one — TikTok returns success to both callers. LockService makes
 * that unreachable.
 *
 * Validation runs here as well as in the browser: the client checks are for
 * fast feedback, these are the ones that actually protect the shop.
 */
function pushSku_(body, user) {
  var prefix = String(body.shop_id || '').toUpperCase();
  var shop = shopById_(prefix);
  if (!shop) throw new Error('Unknown shop: ' + body.shop_id);

  if (!body.identifier || /\s/.test(body.identifier)) {
    throw new Error('SKU identifier is required and cannot contain spaces.');
  }
  if (!(Number(body.price) > 0)) throw new Error('Price must be more than zero.');
  var stock = Number(body.stock);
  if (!(stock >= 1 && stock <= 99999)) throw new Error('Stock must be between 1 and 99,999.');
  if (!body.photo_base64 && !body.tiktok_image_uri) throw new Error('A photo is required.');

  // The variant name is the ONLY text a SKU contributes. The product title
  // belongs to the listing and is set once, so it is validated only on the
  // path that creates one — holding a variation to a product title's
  // 25-character floor rejected every short variant name.
  var variantProblem = validateVariantName_(variantValueName_(body.identifier, body.variant_name));
  if (variantProblem) throw new Error(variantProblem);

  if (!body.listing_id) {
    var titleProblem = validateTitle_(body.title);
    if (titleProblem) throw new Error(titleProblem);
  }

  // NO LOCK IS TAKEN HERE, deliberately.
  //
  // `pushSku` is in Api.gs's WRITE_ACTIONS, so the router already holds the
  // script lock for the whole call. Apps Script locks are not re-entrant —
  // LockService.getScriptLock() hands back a fresh Lock object, and a second
  // tryLock inside the same execution contends with the one the router holds
  // and fails. Locking again here would make every push report itself busy.
  //
  // The router's lock is what makes the read-modify-write below safe: adding a
  // variation reads the product's whole SKU list and sends it back, and two of
  // those at once is a lost update whose consequence is a *deleted* variation
  // rather than an overwritten one, with TikTok returning success to both. If
  // this function is ever called from somewhere that is not the router, that
  // caller must take the script lock itself.
  {
    // A retry after a timeout arrives with the same key. Returning the original
    // product is what makes the offline queue safe.
    if (body.idempotency_key) {
      var prior = findByIdempotencyKey_(body.idempotency_key);
      if (prior) {
        return {
          mode: prior.tiktok_product_id === body.listing_id ? 'variation_added' : 'listing_created',
          listing_id: prior.tiktok_product_id,
          product_id: prior.tiktok_product_id,
          deduplicated: true
        };
      }
    }

    // Archive the photo under the creator's name, then hand copies to TikTok —
    // it refuses external image URLs, so it needs its own uploads.
    var photoUrl = '';
    var imageUri = body.tiktok_image_uri || '';
    var attributeImageUri = body.tiktok_attribute_image_uri || '';
    if (body.photo_base64) {
      photoUrl = savePhoto_(prefix, body.identifier, body.photo_base64,
                            body.photo_mime || 'image/jpeg', user.name);
      var blob = Utilities.newBlob(
        Utilities.base64Decode(body.photo_base64),
        body.photo_mime || 'image/jpeg', 'product.jpg'
      );
      // Only the SKU that creates a listing needs a MAIN_IMAGE; every other
      // one is a variation and needs only the attribute image. Uploading just
      // what is needed halves the calls on the common path.
      attributeImageUri = ttUploadImage_(prefix, blob, 'ATTRIBUTE_IMAGE');
      if (!body.listing_id) imageUri = ttUploadImage_(prefix, blob, 'MAIN_IMAGE');
      else if (!imageUri) imageUri = attributeImageUri;
    }

    var addition = {
      identifier: body.identifier,
      variantName: body.variant_name || '',
      price: body.price,
      stock: stock,
      imageUri: attributeImageUri || imageUri
    };

    return body.listing_id
      ? addVariation_(body, user, prefix, shop, addition, photoUrl)
      : startNewListing_(body, user, prefix, shop, addition, imageUri, attributeImageUri, photoUrl);
  }
}

/** Add a variation to the listing this stream is already using. */
function addVariation_(body, user, prefix, shop, addition, photoUrl) {
  var listingId = String(body.listing_id);
  var snapshot = ttGetProduct_(prefix, listingId);

  // Idempotency from the snapshot rather than from the Sheet.
  //
  // TikTok's `idempotency_key` only exists on Create Product, so an append that
  // times out on factory Wi-Fi has no server-side guard. It does not need one:
  // the product itself records whether this identifier is already a variation,
  // and that answer is authoritative.
  for (var i = 0; i < snapshot.skus.length; i++) {
    if (snapshot.skus[i].sellerSku === addition.identifier) {
      return {
        mode: 'variation_added', deduplicated: true,
        listing_id: listingId, product_id: snapshot.productId,
        sku_id: snapshot.skus[i].id,
        variations_now: snapshot.skus.length,
        remaining: MAX_SKUS_PER_PRODUCT - snapshot.skus.length
      };
    }
  }

  var payload;
  try {
    payload = buildAppendPayload_(snapshot, addition);
  } catch (e) {
    if (String(e.message) === 'LISTING_FULL') {
      // Not a failure — the run has outgrown one product. Say so in a way the
      // client can act on, and record nothing: the SKU is still to be listed.
      var full = new Error('This listing is full at ' + MAX_SKUS_PER_PRODUCT +
        ' variations, which is TikTok\'s limit for Singapore. Start a continuation ' +
        'listing to carry on.');
      full.code = 'LISTING_FULL';
      full.listingId = listingId;
      full.skuCount = snapshot.skus.length;
      throw full;
    }
    throw e;
  }

  var edited = ttFetch_(prefix, 'post',
    '/product/202509/products/' + listingId + '/partial_edit', {}, payload);
  if (edited.code !== 0) {
    recordFailure_(body, user, prefix, shop, photoUrl, addition.imageUri, '', edited.message);
    // TikTok's own wording, verbatim. "You haven't set the return warehouse" is
    // actionable; "push failed" is not.
    throw new Error(edited.message || 'TikTok refused the variation.');
  }

  var skuId = '';
  var returned = (edited.data && edited.data.skus) || [];
  for (var j = 0; j < returned.length; j++) {
    if (returned[j].seller_sku === addition.identifier) skuId = returned[j].id || '';
  }

  var variationsNow = snapshot.skus.length + 1;
  recordSku_(skuRow_(body, user, prefix, shop, addition, photoUrl, '', snapshot.productId));
  logEvent_(user.name, 'add_variation', shop.brand,
    addition.identifier + ' -> ' + listingId + ' (' + variationsNow + '/' +
    MAX_SKUS_PER_PRODUCT + ')', 'ok');

  return {
    mode: 'variation_added',
    listing_id: listingId, product_id: snapshot.productId, sku_id: skuId,
    variant_name: variantValueName_(addition.identifier, addition.variantName),
    variations_now: variationsNow,
    remaining: MAX_SKUS_PER_PRODUCT - variationsNow,
    // Adding a variation resends the product for review. The existing
    // variations stay live and buyable throughout — "If the audit passes, v2 is
    // published to the shop, otherwise the existing product stays live and
    // remains unchanged" — but the new one is not purchasable until it clears.
    // Saying so is the difference between a confusing wait and an expected one.
    audit: 'pending'
  };
}

/**
 * Create the listing this stream will add variations to.
 *
 * Order of operations matters — it is what avoids the two commonest failures:
 *   1. resolve a LEAF category (products cannot be created in a branch),
 *   2. fetch that category's mandatory attributes and fill them,
 *   3. dry-run with listing_check, so problems are named before they cost a
 *      slot against the daily upload cap,
 *   4. create.
 */
function startNewListing_(body, user, prefix, shop, addition, imageUri, attributeImageUri, photoUrl) {
  // A continuation listing takes its title from the listing it continues, read
  // from TikTok rather than from the client — authoritative, and it means
  // nobody has to invent a product name mid-broadcast.
  var title = String(body.title || '').trim();
  if (body.continues_from) {
    var parent = ttGetProduct_(prefix, body.continues_from);
    if (!parent.title) {
      throw new Error('Could not read the title of the listing this continues, so the new one ' +
        'cannot be named. Try again in a moment.');
    }
    title = continuationTitle_(parent.title);
  }
  var titleProblem = validateTitle_(title);
  if (titleProblem) throw new Error(titleProblem);

  var input = {
    title: title,
    identifier: addition.identifier,
    variantName: addition.variantName,
    price: addition.price,
    stock: addition.stock,
    weightKg: body.weight_kg || DEFAULT_WEIGHT_KG,
    imageUri: imageUri,
    attributeImageUri: attributeImageUri,
    idempotencyKey: body.idempotency_key || Utilities.getUuid()
  };

  var categoryId = ttRecommendCategory_(prefix, input.title, input.imageUri);
  var attributes = ttRequiredAttributes_(prefix, categoryId);
  var warehouseId = ttWarehouseId_(prefix);
  var payload = buildPayload_(input, categoryId, warehouseId, attributes);

  // Dry run first: a rejection at create time still counts against the daily
  // allowance, and during a livestream that allowance is the scarce resource.
  var check = ttFetch_(prefix, 'post', '/product/202309/products/listing_check', {}, payload);
  if (check.code !== 0) {
    recordFailure_(body, user, prefix, shop, photoUrl, input.imageUri, categoryId, check.message);
    throw new Error(check.message || 'Listing check failed.');
  }

  var created = ttFetch_(prefix, 'post', '/product/202309/products', {}, payload);
  if (created.code !== 0 || !created.data || !created.data.product_id) {
    recordFailure_(body, user, prefix, shop, photoUrl, input.imageUri, categoryId,
      created.message || 'no product id returned');
    throw new Error(created.message || 'TikTok returned no product ID.');
  }

  var productId = created.data.product_id;
  recordSku_(skuRow_(body, user, prefix, shop, addition, photoUrl, categoryId, productId));
  // Register the new product as this stream's listing, so it appears in the
  // picker and every later SKU can be appended to it.
  addListing_(prefix, productId, user.name);
  logEvent_(user.name, 'create_listing', shop.brand,
    input.identifier + ' ' + input.title + ' -> ' + productId, 'ok');

  return {
    mode: 'listing_created',
    // The new product id IS the listing id for everything that follows, which
    // is why it is returned under both names: the client stores it as the
    // stream's listing, and every later SKU appends to it.
    listing_id: productId, product_id: productId,
    variant_name: variantValueName_(input.identifier, input.variantName),
    variations_now: 1, remaining: MAX_SKUS_PER_PRODUCT - 1,
    photo_url: photoUrl, audit: 'pending'
  };
}

/** One SKU row for the Sheet, so the two success paths cannot drift. */
function skuRow_(body, user, prefix, shop, addition, photoUrl, categoryId, productId) {
  var now = new Date().toISOString();
  return {
    sku_id: Utilities.getUuid(),
    listing_id: productId, shop_id: prefix, brand: shop.brand,
    identifier: addition.identifier, title: String(body.title).trim(),
    variant: variantValueName_(addition.identifier, addition.variantName),
    price: addition.price, stock: addition.stock,
    weight_kg: body.weight_kg || DEFAULT_WEIGHT_KG,
    dims_cm: DEFAULT_DIMS.length + 'x' + DEFAULT_DIMS.width + 'x' + DEFAULT_DIMS.height,
    tiktok_image_uri: addition.imageUri, photo_url: photoUrl,
    category_id: categoryId || '',
    status: 'pushed', error: '', tiktok_product_id: productId,
    idempotency_key: body.idempotency_key || '',
    created_at: now, pushed_at: now, created_by: user.name
  };
}

/** Record a rejection, so the SKU is not lost and the reason is visible. */
function recordFailure_(body, user, prefix, shop, photoUrl, imageUri, categoryId, message) {
  recordSku_({
    sku_id: Utilities.getUuid(), listing_id: body.listing_id, shop_id: prefix,
    brand: shop.brand, identifier: body.identifier, title: body.title,
    variant: body.variant_name || '', price: body.price, stock: body.stock,
    weight_kg: body.weight_kg || DEFAULT_WEIGHT_KG,
    dims_cm: DEFAULT_DIMS.length + 'x' + DEFAULT_DIMS.width + 'x' + DEFAULT_DIMS.height,
    tiktok_image_uri: imageUri, photo_url: photoUrl, category_id: categoryId,
    status: 'failed', error: String(message).slice(0, 500), tiktok_product_id: '',
    idempotency_key: body.idempotency_key || '',
    created_at: new Date().toISOString(), pushed_at: '',
    created_by: user.name
  });
  logEvent_(user.name, 'push_sku', shop.brand, body.identifier + ' — ' + message, 'failed');
}


// =============================================================== Export.gs

/**
 * Exports and photo filing, into dated folders in the shared drive.
 *
 * Structure, created on demand:
 *
 *   TikTok Livestream Buddy/
 *     Exports/2026/2026-09/2026-09-04/
 *       HOUZE - Katrin BJ Live - Brien Chua - 2026-09-04 1432.xlsx
 *     Product Photos/2026-09-04/HZ/
 *       A1 - Brien Chua - 1730.jpg
 *
 * Year and month levels exist so the folder list stays navigable — a flat
 * folder of dated exports is unusable after a few months of daily streams.
 * The creator's name is in the filename because Brien asked for files to carry
 * who made them, and a name in the filename survives being downloaded or
 * moved in a way that Drive metadata does not.
 */

function sgtDate_(d) {
  return Utilities.formatDate(d || new Date(), 'Asia/Singapore', 'yyyy-MM-dd');
}
function sgtStamp_(d) {
  return Utilities.formatDate(d || new Date(), 'Asia/Singapore', 'yyyy-MM-dd HHmm');
}

/** Find or create a child folder. Never creates a duplicate. */
function childFolder_(parent, name) {
  var it = parent.getFoldersByName(name);
  return it.hasNext() ? it.next() : parent.createFolder(name);
}

/** Exports/YYYY/YYYY-MM/YYYY-MM-DD, created as needed. */
function datedExportFolder_(date) {
  var d = date || new Date();
  var day = sgtDate_(d);
  var root = DriveApp.getFolderById(EXPORTS_FOLDER_ID);
  var year = childFolder_(root, day.slice(0, 4));
  var month = childFolder_(year, day.slice(0, 7));
  return childFolder_(month, day);
}

/** Product Photos/YYYY-MM-DD/{shop}, created as needed. */
function datedPhotoFolder_(shopId, date) {
  var root = DriveApp.getFolderById(PHOTOS_FOLDER_ID);
  var day = childFolder_(root, sgtDate_(date));
  return childFolder_(day, shopId);
}

/**
 * File a product photo under the creator's name.
 *
 * Returns the Drive URL. This is our own archive — TikTok refuses external
 * image URLs, so the copy it lists is uploaded to TikTok separately.
 */
function savePhoto_(shopId, identifier, base64, mimeType, creatorName) {
  var folder = datedPhotoFolder_(shopId);
  var ext = (mimeType || 'image/jpeg').indexOf('png') > -1 ? 'png' : 'jpg';
  var name = identifier + ' - ' + safeName_(creatorName) + ' - ' +
    Utilities.formatDate(new Date(), 'Asia/Singapore', 'HHmm') + '.' + ext;
  var blob = Utilities.newBlob(Utilities.base64Decode(base64), mimeType || 'image/jpeg', name);
  var file = folder.createFile(blob);
  return file.getUrl();
}

/**
 * Export a listing's SKUs as a real .xlsx into today's dated folder.
 *
 * Built by writing a temporary Google Sheet and exporting it, which is the
 * only way to produce genuine xlsx from Apps Script — a CSV renamed .xlsx
 * opens with a warning in Excel and Brien asked for Excel.
 */
function exportListing_(listingId, actor) {
  var skus = listSkus_(listingId).filter(function (s) { return String(s.status) === 'pushed'; });
  var listing = readAll_(TAB_LISTINGS).filter(function (l) {
    return String(l.listing_id) === String(listingId);
  })[0];
  if (!listing) throw new Error('Unknown listing: ' + listingId);

  var header = ['Identifier', 'Title', 'Variant', 'Price (SGD)', 'Stock', 'Weight (kg)', 'Dimensions (cm)', 'TikTok product ID', 'Listed at (SGT)', 'Created by'];
  var rows = skus.map(function (s) {
    return [s.identifier, s.title, s.variant, s.price, s.stock, s.weight_kg, s.dims_cm, s.tiktok_product_id, s.pushed_at, s.created_by || ''];
  });

  var temp = SpreadsheetApp.create('tikshop-export-temp');
  try {
    var sh = temp.getActiveSheet();
    sh.getRange(1, 1, 1, header.length).setValues([header]).setFontWeight('bold');
    if (rows.length) sh.getRange(2, 1, rows.length, header.length).setValues(rows);
    sh.setFrozenRows(1);
    SpreadsheetApp.flush();

    var url = 'https://docs.google.com/spreadsheets/d/' + temp.getId() +
      '/export?format=xlsx&portrait=false';
    var blob = UrlFetchApp.fetch(url, {
      headers: { Authorization: 'Bearer ' + ScriptApp.getOAuthToken() }
    }).getBlob();

    var filename = (listing.brand || listing.shop_id) + ' - ' +
      safeName_(listing.product_name || listingId) + ' - ' +
      safeName_(actor) + ' - ' + sgtStamp_() + '.xlsx';
    blob.setName(filename);

    var file = datedExportFolder_().createFile(blob);
    logEvent_(actor, 'export', listing.brand, filename + ' (' + rows.length + ' SKUs)', 'ok');
    return { url: file.getUrl(), name: filename, rows: rows.length };
  } finally {
    // The temporary sheet is always removed, including when the export throws
    // — otherwise a failed export litters the drive with temp files.
    try { DriveApp.getFileById(temp.getId()).setTrashed(true); } catch (e) { /* already gone */ }
  }
}


// ================================================================== Api.gs

/**
 * The JSON API.
 *
 * Same shape as Sheldon Delivery API — `?action=` routing, LockService around
 * writes — so the two projects read alike.
 *
 * Every action except `ping` requires a verified Google identity AND an
 * approved role. Authentication proves who someone is; the allowlist decides
 * whether they may act. Conflating the two is how an app that pushes to live
 * shops ends up open to anyone with a Google account.
 */

function doGet(e) {
  // TikTok sends the seller back as {redirect_url}?code=...&state=...
  // Checked before anything else, or the callback would be treated as an API
  // call and the authorisation silently lost.
  if (e && e.parameter && e.parameter.code && !e.parameter.action) {
    return ttHandleAuthCallback_(e);
  }
  return handle_(e, 'GET');
}

function doPost(e) {
  return handle_(e, 'POST');
}

/** Actions that must serialise, because they read-then-write the Sheet. */
var WRITE_ACTIONS = {
  addListing: 1, saveSku: 1, pushSku: 1, exportListing: 1, setRole: 1
};

/** Actions callable without an approved role. */
var OPEN_ACTIONS = { ping: 1, whoami: 1 };

function handle_(e, method) {
  var action = (e && e.parameter && e.parameter.action) || 'ping';
  var body = {};
  if (method === 'POST' && e && e.postData && e.postData.contents) {
    try { body = JSON.parse(e.postData.contents); } catch (err) { body = {}; }
  }
  var params = e && e.parameter ? e.parameter : {};

  try {
    if (action === 'ping') return json_({ ok: true, time: new Date().toISOString() });

    // Identity comes from a Google ID token the frontend forwards, verified
    // against Google — never from a claim the caller simply asserts.
    var identity = verifyIdToken_(body.id_token || params.id_token);
    if (!identity.ok) {
      // The reason travels with the refusal. Every one of these used to read
      // "Sign in with Google to continue.", so a backend that was merely
      // misconfigured looked exactly like a user who had not signed in — and
      // the screen looped with nothing to act on.
      return json_({ error: identity.message, code: identity.code }, 401);
    }

    var user = resolveUser_(identity);

    if (action === 'whoami') {
      return json_({
        email: user.email, name: user.name, role: user.role,
        approved: canList_(user), admin: isAdmin_(user)
      });
    }

    if (!canList_(user)) {
      // Deliberately explicit: a person waiting for approval should know that
      // is what is happening, not see a generic refusal.
      return json_({
        error: user.role === ROLE_BLOCKED
          ? 'This account has been blocked.'
          : 'Your account is awaiting approval. Ask Brien to approve ' + user.email + '.',
        role: user.role
      }, 403);
    }

    // One lock for the whole write, taken here and nowhere deeper. Everything
    // below assumes it is held; see Lock.gs for why nesting it is a trap.
    if (WRITE_ACTIONS[action]) {
      return withScriptLock_(30000, function () {
        return route_(action, params, body, user);
      });
    }
    return route_(action, params, body, user);
  } catch (err) {
    var message = String(err && err.message ? err.message : err);

    // Two outcomes reach here that are not failures, and the client has to be
    // able to tell them apart from a genuine one — retrying a rejected listing
    // burns the shop's daily allowance, while NOT retrying a busy one loses a
    // SKU mid-livestream.

    // The listing filled up. Singapore allows 100 variations per product, so a
    // long factory run simply outgrows one; the client offers a continuation
    // listing rather than showing an error.
    if (err && err.code === 'LISTING_FULL') {
      return json_({
        error: message, code: 'LISTING_FULL',
        product_id: err.listingId || '', sku_count: err.skuCount || 0,
        max_skus: MAX_SKUS_PER_PRODUCT, next: 'start_new_listing'
      }, 409);
    }

    // Another write holds the lock. Retryable, and nothing has been lost.
    if (/^BUSY:/.test(message)) {
      return json_({
        error: message.replace(/^BUSY:\s*/, ''), code: 'LISTING_BUSY', retryable: true
      }, 409);
    }

    // Log the detail, return something safe. A stack trace in a response body
    // is information disclosure.
    console.error(action + ' failed: ' + err + (err && err.stack ? '\n' + err.stack : ''));
    logEvent_((params && params.actor) || 'unknown', action, '', message, 'error');

    // A rejection from TikTok is the operator's to act on, so its own wording
    // goes through verbatim — "you haven't set the return warehouse" is
    // actionable, "push failed" is not. 422 rather than 500: the request was
    // understood and refused, and the client must not retry it.
    return json_({ error: message }, action === 'pushSku' ? 422 : 500);
  }
}

function route_(action, params, body, user) {
  switch (action) {
    case 'shops':
      return json_(shopsForClient_());

    case 'listings':
      return json_(listListings_(params.shop_id || body.shop_id));

    // Reads its arguments from either place, like the read actions above.
    //
    // Not for tidiness: when a browser mishandles the redirect Apps Script
    // answers through, the client retries the same call as a GET, and an
    // action that only looks at the body would refuse it. This one is on the
    // critical path — no listing means no stream to add SKUs to — so it must
    // survive that retry. pushSku deliberately does not, because a photo does
    // not fit in a URL; it is protected by its idempotency key instead.
    case 'addListing':
      return json_(addListing_(
        params.shop_id || body.shop_id,
        params.listing_id || body.listing_id,
        user.name
      ));

    case 'skus':
      return json_(listSkus_(params.listing_id || body.listing_id));

    case 'allowance':
      var shopId = params.shop_id || body.shop_id;
      var used = pushedToday_(shopId);
      return json_({ used: used, cap: Number(prop_(shopId + '_DAILY_CAP') || 1000),
                     remaining: Math.max(0, Number(prop_(shopId + '_DAILY_CAP') || 1000) - used) });

    case 'pushSku':
      return json_(pushSku_(body, user));

    case 'exportListing':
      return json_(exportListing_(params.listing_id || body.listing_id, user.name));

    case 'users':
      if (!isAdmin_(user)) return json_({ error: 'Admins only.' }, 403);
      return json_(usersAll_());

    // Left POST-only on purpose. It is an admin action taken once in a while,
    // never mid-stream, so it does not need to survive a broken redirect — and
    // the fewer ways there are to change someone's role, the better.
    case 'setRole':
      if (!isAdmin_(user)) return json_({ error: 'Admins only.' }, 403);
      return json_(setRole_(body.email, body.role, user));

    default:
      return json_({ error: 'Unknown action: ' + action }, 400);
  }
}

function shopsForClient_() {
  return SHOPS.map(function (s) {
    return {
      shop_id: s.id,
      brand: s.brand,
      tiktok_handle: s.handle,
      entity: s.entity,
      authorised: Boolean(prop_(s.id + '_ACCESS_TOKEN')),
      daily_listing_cap: Number(prop_(s.id + '_DAILY_CAP') || 1000)
    };
  });
}

/** Change someone's role. Admins only, and the owner cannot be demoted. */
function setRole_(email, role, actor) {
  var target = String(email || '').toLowerCase();
  var allowed = [ROLE_ADMIN, ROLE_LISTER, ROLE_PENDING, ROLE_BLOCKED];
  if (allowed.indexOf(role) === -1) throw new Error('Unknown role: ' + role);
  if (target === String(OWNER_EMAIL).toLowerCase() && role !== ROLE_ADMIN) {
    // Without this, one mistake locks everyone out of approving anyone.
    throw new Error('The owner account cannot be demoted.');
  }

  var sh = sheet_(TAB_USERS);
  var last = sh.getLastRow();
  for (var i = 2; i <= last; i++) {
    if (String(sh.getRange(i, 1).getValue()).toLowerCase() === target) {
      sh.getRange(i, 3).setValue(role);
      sh.getRange(i, 6).setValue(actor.email);
      logEvent_(actor.name, 'set_role', '', target + ' -> ' + role, 'ok');
      return { email: target, role: role };
    }
  }
  throw new Error('No such user: ' + target);
}

function json_(obj, status) {
  // Apps Script web apps always answer 200; the status is carried in the body
  // so the frontend can branch on it.
  if (status) obj._status = status;
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}
